<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Status</name>
   <tag></tag>
   <elementGuidId>63d10912-a30a-4614-a5c6-c0491818f1d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dropdownMenuButton1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdownMenuButton1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8e76dfe5-a338-4dc4-895d-25b002ddde90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-white dropdown-toggle show</value>
      <webElementGuid>169f2d7f-4cd7-4f1b-b783-801358a4c6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9efbf7e3-f3c5-4b7a-8491-027b2a8ad18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownMenuButton1</value>
      <webElementGuid>7aa2fcd8-3ba8-4fc6-bf62-608ab6f9930d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>d86772d4-c8fd-49c9-bfc0-a97959d6e733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1a1ae0c9-c43c-4221-a6c0-178e5b520694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1bc019fa-0f9b-4a75-9743-1a4f83a4fe4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Status 
                                          </value>
      <webElementGuid>9d62a233-8264-47e4-bc7c-8e89819849b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/main[@class=&quot;col-md-9 ml-sm-auto col-lg-10 px-md-4 py-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-xl-12 mb-4 mb-lg-0&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[3]/div[@class=&quot;dropdown&quot;]/button[@id=&quot;dropdownMenuButton1&quot;]</value>
      <webElementGuid>532be4ae-f236-4e11-9611-608754ba543d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dropdownMenuButton1']</value>
      <webElementGuid>cc9b11a7-1a9f-4016-ba81-96bb95b0abff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun Apr 02 2023 20:42:05 GMT+0000 (Coordinated Universal Time)'])[1]/following::button[1]</value>
      <webElementGuid>d3bcf6aa-c2e9-486d-9ab2-d3dabda643d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test2'])[1]/following::button[1]</value>
      <webElementGuid>fd210806-9cb8-4d15-9771-ecad3da1f499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test2'])[2]/preceding::button[1]</value>
      <webElementGuid>56bb8cc2-9661-494c-ac6e-b309dfb03ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun Apr 02 2023 20:43:32 GMT+0000 (Coordinated Universal Time)'])[1]/preceding::button[1]</value>
      <webElementGuid>d474d1aa-d733-41a7-a1a0-b38e449bb9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/button</value>
      <webElementGuid>f4156265-4d52-4ccf-8250-4776798411a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dropdownMenuButton1' and (text() = '
                                            Status 
                                          ' or . = '
                                            Status 
                                          ')]</value>
      <webElementGuid>53709cae-62db-4992-851b-0a6ccc16e3b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
