<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_On Cooking</name>
   <tag></tag>
   <elementGuidId>a40df85a-42e7-4194-b4ab-510ba0f444e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dropdownMenuButton1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdownMenuButton1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bcd8ed06-872f-4226-8183-5edc0717c545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-white dropdown-toggle show</value>
      <webElementGuid>1e2e9a7f-7190-4540-9050-5fa3a07de312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12845495-d606-4a71-b0e6-b86b6b323e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownMenuButton1</value>
      <webElementGuid>aae2321f-bf93-4bcd-a064-25052e6341f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>21b344ff-88f0-48b0-b885-4fe6a0c9d25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5e92cd9b-3242-4bc0-b698-c1f121ad0d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>521c9af3-85e5-4f66-b995-e510d2922ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>On Cooking</value>
      <webElementGuid>63cc1c37-fe45-4f5a-b612-662530c666ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/main[@class=&quot;col-md-9 ml-sm-auto col-lg-10 px-md-4 py-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-xl-12 mb-4 mb-lg-0&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[3]/div[@class=&quot;dropdown&quot;]/button[@id=&quot;dropdownMenuButton1&quot;]</value>
      <webElementGuid>b1c1d1a7-9477-4908-9352-76eb4f915c66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dropdownMenuButton1']</value>
      <webElementGuid>3315bd8d-0d68-4921-a271-bfa9824e1b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun Apr 02 2023 20:42:05 GMT+0000 (Coordinated Universal Time)'])[1]/following::button[1]</value>
      <webElementGuid>3bf7e3e8-4e29-4c25-a0c2-10483e4b433a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test2'])[1]/following::button[1]</value>
      <webElementGuid>2cd12a03-e542-47f0-933d-e362b22b9d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test2'])[2]/preceding::button[1]</value>
      <webElementGuid>0902d01e-d77a-4a0a-97b2-76f022f4e496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun Apr 02 2023 20:43:32 GMT+0000 (Coordinated Universal Time)'])[1]/preceding::button[1]</value>
      <webElementGuid>f8eec6c6-ee4e-4e5f-9639-a6d27f22b732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='On Cooking']/parent::*</value>
      <webElementGuid>a89e5df9-7eba-45aa-bbe7-930a25b8721e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/button</value>
      <webElementGuid>4ad433f8-1d76-46ba-a31d-bdd55556f807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dropdownMenuButton1' and (text() = 'On Cooking' or . = 'On Cooking')]</value>
      <webElementGuid>c21bd9ba-e809-49c8-97d3-489cab455bc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
