<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Master Login_adminusersname</name>
   <tag></tag>
   <elementGuidId>8a180e54-7ead-40a5-9f7e-785eaed73ec6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floatingInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#floatingInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3e092de-8d00-41e6-97de-eaf70cf511d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>adminusersname</value>
      <webElementGuid>08c98053-f891-44c2-ab8b-833dbdf78833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae83b133-5946-433a-8603-1db933084c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded-3</value>
      <webElementGuid>34b854bd-c47a-41ef-a1ed-c71c341d7771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floatingInput</value>
      <webElementGuid>a67dc37b-0b86-47f7-859a-2d270a0688d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>c2455de5-e7d7-4240-a209-9c2074b69098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floatingInput&quot;)</value>
      <webElementGuid>b65420c2-6554-4199-b937-a6ff25cd06de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floatingInput']</value>
      <webElementGuid>bbff061f-f93e-4c9e-b2e4-d525b612e378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1851aef8-9880-46d5-9ab7-77abf3183f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'adminusersname' and @type = 'text' and @id = 'floatingInput' and @placeholder = 'username']</value>
      <webElementGuid>0f6c8360-ebda-4145-8286-21f27b241043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
