<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Get Started</name>
   <tag></tag>
   <elementGuidId>dc58eb89-d47f-4808-a744-505b323d99ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='heroCarousel']/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn-get-started.scrollto.animate__animated.animate__fadeInUp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ca199e2-a725-44d3-aded-5439dd38acb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>picorder</value>
      <webElementGuid>70307563-3206-43c2-b7b9-d7e0fb06643e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-get-started scrollto animate__animated animate__fadeInUp</value>
      <webElementGuid>a7513294-ffda-42ad-a0bb-b55fca437151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Started</value>
      <webElementGuid>0fcbf92d-f323-457d-9172-fb2d18fbe8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;heroCarousel&quot;)/div[@class=&quot;carousel-inner&quot;]/div[@class=&quot;carousel-item active&quot;]/div[@class=&quot;carousel-container&quot;]/div[@class=&quot;container&quot;]/a[@class=&quot;btn-get-started scrollto animate__animated animate__fadeInUp&quot;]</value>
      <webElementGuid>e635b999-fc6e-4c1d-a3bd-689dd2c135cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='heroCarousel']/div/div/div/div/a</value>
      <webElementGuid>ed4d6e43-a8c8-4803-8cac-c77d1073c5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Get Started')]</value>
      <webElementGuid>356e8bf4-7e05-4064-80eb-15dc757c4c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome ! test2'])[1]/following::a[1]</value>
      <webElementGuid>40878edb-827f-493b-b592-0ff451218824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Place Order'])[1]/following::a[1]</value>
      <webElementGuid>34149650-6662-41b4-b055-713d53447458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TiguS - Kawmunkai'])[1]/preceding::a[1]</value>
      <webElementGuid>8957223f-1a8b-455b-bc84-2b2c522d3642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Menu'])[1]/preceding::a[1]</value>
      <webElementGuid>79a3b64c-0a2d-4dac-a362-15b8d6c185b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get Started']/parent::*</value>
      <webElementGuid>e0858468-7da4-4b9d-a6e8-debe3b29eb53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'picorder')])[2]</value>
      <webElementGuid>f982e045-dd12-47ee-b0ad-e1e30f475f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>8bb716f5-a38c-4fbd-b4d2-af615ac39cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'picorder' and (text() = 'Get Started' or . = 'Get Started')]</value>
      <webElementGuid>502df078-79cb-4780-b907-57489724c4f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
